/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.public_.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.public_.tables.CrumbMisfits;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CrumbMisfitsRecord extends UpdatableRecordImpl<CrumbMisfitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CRUMB_MISFITS.LINE</code>.
     */
    public void setLine(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CRUMB_MISFITS.LINE</code>.
     */
    public Integer getLine() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrumbMisfitsRecord
     */
    public CrumbMisfitsRecord() {
        super(CrumbMisfits.CRUMB_MISFITS);
    }

    /**
     * Create a detached, initialised CrumbMisfitsRecord
     */
    public CrumbMisfitsRecord(Integer line) {
        super(CrumbMisfits.CRUMB_MISFITS);

        setLine(line);
        resetChangedOnNotNull();
    }
}
