/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.public_.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Ctx;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CtxRecord extends UpdatableRecordImpl<CtxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CTX.LINE</code>.
     */
    public void setLine(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.LINE</code>.
     */
    public Integer getLine() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTX.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTX.THREAD</code>.
     */
    public void setThread(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.THREAD</code>.
     */
    public String getThread() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTX.PATTERN</code>.
     */
    public void setPattern(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.PATTERN</code>.
     */
    public String getPattern() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTX.CONCUR_CTX</code>.
     */
    public void setConcurCtx(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.CONCUR_CTX</code>.
     */
    public String getConcurCtx() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTX.ASSESS_CTX</code>.
     */
    public void setAssessCtx(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.ASSESS_CTX</code>.
     */
    public String getAssessCtx() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTX.APP_CTX</code>.
     */
    public void setAppCtx(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.APP_CTX</code>.
     */
    public String getAppCtx() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CTX.TASK_CLASS</code>.
     */
    public void setTaskClass(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.TASK_CLASS</code>.
     */
    public String getTaskClass() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CTX.TASK_OBJ</code>.
     */
    public void setTaskObj(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.TASK_OBJ</code>.
     */
    public String getTaskObj() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CTX.WRAP_INIT</code>.
     */
    public void setWrapInit(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.WRAP_INIT</code>.
     */
    public String getWrapInit() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.CTX.RUNNABLE</code>.
     */
    public void setRunnable(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.RUNNABLE</code>.
     */
    public String getRunnable() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.CTX.TRACE_MAP</code>.
     */
    public void setTraceMap(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.CTX.TRACE_MAP</code>.
     */
    public String getTraceMap() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtxRecord
     */
    public CtxRecord() {
        super(Ctx.CTX);
    }

    /**
     * Create a detached, initialised CtxRecord
     */
    public CtxRecord(Integer line, LocalDateTime timestamp, String thread, String pattern, String concurCtx, String assessCtx, String appCtx, String taskClass, String taskObj, String wrapInit, String runnable, String traceMap) {
        super(Ctx.CTX);

        setLine(line);
        setTimestamp(timestamp);
        setThread(thread);
        setPattern(pattern);
        setConcurCtx(concurCtx);
        setAssessCtx(assessCtx);
        setAppCtx(appCtx);
        setTaskClass(taskClass);
        setTaskObj(taskObj);
        setWrapInit(wrapInit);
        setRunnable(runnable);
        setTraceMap(traceMap);
        resetChangedOnNotNull();
    }
}
