/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.public_.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Mesg;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MesgRecord extends UpdatableRecordImpl<MesgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.MESG.LINE</code>.
     */
    public void setLine(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.LINE</code>.
     */
    public Integer getLine() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MESG.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MESG.THREAD</code>.
     */
    public void setThread(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.THREAD</code>.
     */
    public String getThread() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.MESG.LOGGER</code>.
     */
    public void setLogger(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.LOGGER</code>.
     */
    public String getLogger() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.MESG.LEVEL</code>.
     */
    public void setLevel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.LEVEL</code>.
     */
    public String getLevel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.MESG.MESSAGE</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.MESG.MESSAGE</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MesgRecord
     */
    public MesgRecord() {
        super(Mesg.MESG);
    }

    /**
     * Create a detached, initialised MesgRecord
     */
    public MesgRecord(Integer line, LocalDateTime timestamp, String thread, String logger, String level, String message) {
        super(Mesg.MESG);

        setLine(line);
        setTimestamp(timestamp);
        setThread(thread);
        setLogger(logger);
        setLevel(level);
        setMessage(message);
        resetChangedOnNotNull();
    }
}
