/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.public_.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Trak;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrakRecord extends UpdatableRecordImpl<TrakRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.TRAK.LINE</code>.
     */
    public void setLine(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.LINE</code>.
     */
    public Integer getLine() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.THREAD</code>.
     */
    public void setThread(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.THREAD</code>.
     */
    public String getThread() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.TRACE_MAP</code>.
     */
    public void setTraceMap(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.TRACE_MAP</code>.
     */
    public String getTraceMap() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.TRACKED_OBJ</code>.
     */
    public void setTrackedObj(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.TRACKED_OBJ</code>.
     */
    public String getTrackedObj() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.TRACE_NUM</code>.
     */
    public void setTraceNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.TRACE_NUM</code>.
     */
    public Integer getTraceNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.TRAK.TRACE_MAP_SIZE</code>.
     */
    public void setTraceMapSize(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.TRAK.TRACE_MAP_SIZE</code>.
     */
    public Integer getTraceMapSize() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrakRecord
     */
    public TrakRecord() {
        super(Trak.TRAK);
    }

    /**
     * Create a detached, initialised TrakRecord
     */
    public TrakRecord(Integer line, LocalDateTime timestamp, String thread, String traceMap, String trackedObj, Integer traceNum, Integer traceMapSize) {
        super(Trak.TRAK);

        setLine(line);
        setTimestamp(timestamp);
        setThread(thread);
        setTraceMap(traceMap);
        setTrackedObj(trackedObj);
        setTraceNum(traceNum);
        setTraceMapSize(traceMapSize);
        resetChangedOnNotNull();
    }
}
