/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.Constants;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConstantsRecord extends TableRecordImpl<ConstantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_CATALOG</code>.
     */
    public void setConstantCatalog(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_CATALOG</code>.
     */
    public String getConstantCatalog() {
        return (String) get(0);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_SCHEMA</code>.
     */
    public void setConstantSchema(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_SCHEMA</code>.
     */
    public String getConstantSchema() {
        return (String) get(1);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_NAME</code>.
     */
    public void setConstantName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.CONSTANT_NAME</code>.
     */
    public String getConstantName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.VALUE_DEFINITION</code>.
     */
    public void setValueDefinition(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.VALUE_DEFINITION</code>.
     */
    public String getValueDefinition() {
        return (String) get(3);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.DATA_TYPE</code>.
     */
    public void setDataType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.DATA_TYPE</code>.
     */
    public String getDataType() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_MAXIMUM_LENGTH</code>.
     */
    public void setCharacterMaximumLength(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_MAXIMUM_LENGTH</code>.
     */
    public Long getCharacterMaximumLength() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_OCTET_LENGTH</code>.
     */
    public void setCharacterOctetLength(Long value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_OCTET_LENGTH</code>.
     */
    public Long getCharacterOctetLength() {
        return (Long) get(6);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_CATALOG</code>.
     */
    public void setCharacterSetCatalog(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_CATALOG</code>.
     */
    public String getCharacterSetCatalog() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_SCHEMA</code>.
     */
    public void setCharacterSetSchema(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_SCHEMA</code>.
     */
    public String getCharacterSetSchema() {
        return (String) get(8);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_NAME</code>.
     */
    public void setCharacterSetName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.CHARACTER_SET_NAME</code>.
     */
    public String getCharacterSetName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_CATALOG</code>.
     */
    public void setCollationCatalog(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_CATALOG</code>.
     */
    public String getCollationCatalog() {
        return (String) get(10);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_SCHEMA</code>.
     */
    public void setCollationSchema(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_SCHEMA</code>.
     */
    public String getCollationSchema() {
        return (String) get(11);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_NAME</code>.
     */
    public void setCollationName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.COLLATION_NAME</code>.
     */
    public String getCollationName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_PRECISION</code>.
     */
    public void setNumericPrecision(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_PRECISION</code>.
     */
    public Integer getNumericPrecision() {
        return (Integer) get(13);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_PRECISION_RADIX</code>.
     */
    public void setNumericPrecisionRadix(Integer value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_PRECISION_RADIX</code>.
     */
    public Integer getNumericPrecisionRadix() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_SCALE</code>.
     */
    public void setNumericScale(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.NUMERIC_SCALE</code>.
     */
    public Integer getNumericScale() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.DATETIME_PRECISION</code>.
     */
    public void setDatetimePrecision(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.DATETIME_PRECISION</code>.
     */
    public Integer getDatetimePrecision() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.INTERVAL_TYPE</code>.
     */
    public void setIntervalType(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.INTERVAL_TYPE</code>.
     */
    public String getIntervalType() {
        return (String) get(17);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.INTERVAL_PRECISION</code>.
     */
    public void setIntervalPrecision(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.INTERVAL_PRECISION</code>.
     */
    public Integer getIntervalPrecision() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.MAXIMUM_CARDINALITY</code>.
     */
    public void setMaximumCardinality(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.MAXIMUM_CARDINALITY</code>.
     */
    public Integer getMaximumCardinality() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.DTD_IDENTIFIER</code>.
     */
    public void setDtdIdentifier(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.DTD_IDENTIFIER</code>.
     */
    public String getDtdIdentifier() {
        return (String) get(20);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_DATA_TYPE</code>.
     */
    public void setDeclaredDataType(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_DATA_TYPE</code>.
     */
    public String getDeclaredDataType() {
        return (String) get(21);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_NUMERIC_PRECISION</code>.
     */
    public void setDeclaredNumericPrecision(Integer value) {
        set(22, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_NUMERIC_PRECISION</code>.
     */
    public Integer getDeclaredNumericPrecision() {
        return (Integer) get(22);
    }

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_NUMERIC_SCALE</code>.
     */
    public void setDeclaredNumericScale(Integer value) {
        set(23, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.CONSTANTS.DECLARED_NUMERIC_SCALE</code>.
     */
    public Integer getDeclaredNumericScale() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.GEOMETRY_TYPE</code>.
     */
    public void setGeometryType(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.GEOMETRY_TYPE</code>.
     */
    public String getGeometryType() {
        return (String) get(24);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.GEOMETRY_SRID</code>.
     */
    public void setGeometrySrid(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.GEOMETRY_SRID</code>.
     */
    public Integer getGeometrySrid() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.CONSTANTS.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.CONSTANTS.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(26);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConstantsRecord
     */
    public ConstantsRecord() {
        super(Constants.CONSTANTS);
    }

    /**
     * Create a detached, initialised ConstantsRecord
     */
    public ConstantsRecord(String constantCatalog, String constantSchema, String constantName, String valueDefinition, String dataType, Long characterMaximumLength, Long characterOctetLength, String characterSetCatalog, String characterSetSchema, String characterSetName, String collationCatalog, String collationSchema, String collationName, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, Integer datetimePrecision, String intervalType, Integer intervalPrecision, Integer maximumCardinality, String dtdIdentifier, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, String geometryType, Integer geometrySrid, String remarks) {
        super(Constants.CONSTANTS);

        setConstantCatalog(constantCatalog);
        setConstantSchema(constantSchema);
        setConstantName(constantName);
        setValueDefinition(valueDefinition);
        setDataType(dataType);
        setCharacterMaximumLength(characterMaximumLength);
        setCharacterOctetLength(characterOctetLength);
        setCharacterSetCatalog(characterSetCatalog);
        setCharacterSetSchema(characterSetSchema);
        setCharacterSetName(characterSetName);
        setCollationCatalog(collationCatalog);
        setCollationSchema(collationSchema);
        setCollationName(collationName);
        setNumericPrecision(numericPrecision);
        setNumericPrecisionRadix(numericPrecisionRadix);
        setNumericScale(numericScale);
        setDatetimePrecision(datetimePrecision);
        setIntervalType(intervalType);
        setIntervalPrecision(intervalPrecision);
        setMaximumCardinality(maximumCardinality);
        setDtdIdentifier(dtdIdentifier);
        setDeclaredDataType(declaredDataType);
        setDeclaredNumericPrecision(declaredNumericPrecision);
        setDeclaredNumericScale(declaredNumericScale);
        setGeometryType(geometryType);
        setGeometrySrid(geometrySrid);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
