/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.InformationSchemaCatalogName;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InformationSchemaCatalogNameRecord extends TableRecordImpl<InformationSchemaCatalogNameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME.CATALOG_NAME</code>.
     */
    public void setCatalogName(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME.CATALOG_NAME</code>.
     */
    public String getCatalogName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InformationSchemaCatalogNameRecord
     */
    public InformationSchemaCatalogNameRecord() {
        super(InformationSchemaCatalogName.INFORMATION_SCHEMA_CATALOG_NAME);
    }

    /**
     * Create a detached, initialised InformationSchemaCatalogNameRecord
     */
    public InformationSchemaCatalogNameRecord(String catalogName) {
        super(InformationSchemaCatalogName.INFORMATION_SCHEMA_CATALOG_NAME);

        setCatalogName(catalogName);
        resetChangedOnNotNull();
    }
}
