/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.records;


import com.contrtastsecurity.agent.loghog.jooq.information_schema.tables.Users;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends TableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>INFORMATION_SCHEMA.USERS.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.USERS.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.USERS.IS_ADMIN</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.USERS.IS_ADMIN</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.USERS.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.USERS.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String userName, Boolean isAdmin, String remarks) {
        super(Users.USERS);

        setUserName(userName);
        setIsAdmin(isAdmin);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
