/*
 * This file is generated by jOOQ.
 */
package com.contrtastsecurity.agent.loghog.jooq.public_;


import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Cont;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Crumb;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.CrumbMisfits;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Ctx;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.CtxMisfits;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Log;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Mesg;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.Trak;
import com.contrtastsecurity.agent.loghog.jooq.public_.tables.TrakMisfits;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.CONT</code>.
     */
    public static final Cont CONT = Cont.CONT;

    /**
     * The table <code>PUBLIC.CRUMB</code>.
     */
    public static final Crumb CRUMB = Crumb.CRUMB;

    /**
     * The table <code>PUBLIC.CRUMB_MISFITS</code>.
     */
    public static final CrumbMisfits CRUMB_MISFITS = CrumbMisfits.CRUMB_MISFITS;

    /**
     * The table <code>PUBLIC.CTX</code>.
     */
    public static final Ctx CTX = Ctx.CTX;

    /**
     * The table <code>PUBLIC.CTX_MISFITS</code>.
     */
    public static final CtxMisfits CTX_MISFITS = CtxMisfits.CTX_MISFITS;

    /**
     * The table <code>PUBLIC.LOG</code>.
     */
    public static final Log LOG = Log.LOG;

    /**
     * The table <code>PUBLIC.MESG</code>.
     */
    public static final Mesg MESG = Mesg.MESG;

    /**
     * The table <code>PUBLIC.TRAK</code>.
     */
    public static final Trak TRAK = Trak.TRAK;

    /**
     * The table <code>PUBLIC.TRAK_MISFITS</code>.
     */
    public static final TrakMisfits TRAK_MISFITS = TrakMisfits.TRAK_MISFITS;
}
